-- Simple GreptimeDB schema compatible with PostgreSQL protocol - all keywords quoted
CREATE TABLE traces (
    id VARCHAR,
    "timestamp" TIMESTAMP,
    "name" VARCHAR,
    user_id VARCHAR,
    "metadata" TEXT,
    "release" VARCHAR,
    "version" VARCHAR,
    project_id VARCHAR,
    "public" BOOLEAN,
    bookmarked BOOLEAN,
    tags TEXT,
    "input" TEXT,
    "output" TEXT,
    session_id VARCHAR,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE observations (
    id VARCHAR,
    trace_id VARCHAR,
    project_id VARCHAR,
    "type" VARCHAR,
    parent_observation_id VARCHAR,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    "name" VARCHAR,
    "metadata" TEXT,
    "level" VARCHAR,
    status_message VARCHAR,
    "version" VARCHAR,
    "input" TEXT,
    "output" TEXT,
    provided_model_name VARCHAR,
    internal_model_id VARCHAR,
    model_parameters TEXT,
    provided_usage_details TEXT,
    usage_details TEXT,
    provided_cost_details TEXT,
    cost_details TEXT,
    total_cost DECIMAL,
    completion_start_time TIMESTAMP,
    prompt_id VARCHAR,
    prompt_name VARCHAR,
    prompt_version INTEGER,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE scores (
    id VARCHAR,
    "timestamp" TIMESTAMP,
    project_id VARCHAR,
    trace_id VARCHAR,
    observation_id VARCHAR,
    "name" VARCHAR,
    "value" DECIMAL,
    "source" VARCHAR,
    "comment" TEXT,
    author_user_id VARCHAR,
    config_id VARCHAR,
    data_type VARCHAR,
    string_value VARCHAR,
    queue_id VARCHAR,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);